<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Version>3.5.4</Version>
        <Description>TheOtherRoles: GM Edition</Description>
        <Authors>Eisbison</Authors>
    </PropertyGroup>

    <PropertyGroup>
        <DefineConstants>$(DefineConstants);STEAM</DefineConstants>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ApplicationIcon />
        <Win32Resource />
        <AssemblyName>TheOtherRolesGM</AssemblyName>
    </PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\**" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="$(AmongUs)\BepInEx\core\*.dll" />
		<Reference Include="$(AmongUs)\BepInEx\interop\*.dll" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.692" Private="false" ExcludeAssets="runtime;native" />
		<PackageReference Include="BepInEx.IL2CPP.MSBuild" Version="2.0.1" PrivateAssets="all" ExcludeAssets="runtime" />
	</ItemGroup>
	


	<Target Name="CopyCustomContent" AfterTargets="AfterBuild">
        <Message Text="Second occurrence" />
		<Copy SourceFiles="$(ProjectDir)\bin\$(Configuration)\net6.0\TheOtherRolesGM.dll" DestinationFolder="$(AmongUs)/BepInEx/plugins/" />
		<Copy SourceFiles="$(ProjectDir)\bin\$(Configuration)\net6.0\TheOtherRolesGM.dll" DestinationFolder="./libs" />
		<Copy SourceFiles="$(ProjectDir)\bin\$(Configuration)\net6.0\TheOtherRolesGM.dll" DestinationFolder="./libs/TORGM-Restored/BepinEx/plugins" />
    </Target>
<!--
    <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
      <Exec Command="py &quot;$(SolutionDir)stringsToJson.py&quot;" />
    </Target>
-->
</Project>
