<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Version>3.5.4</Version>
        <Description>TheOtherRoles: GM Edition</Description>
        <Authors>Eisbison</Authors>
    </PropertyGroup>

    <PropertyGroup>
        <DefineConstants>$(DefineConstants);STEAM</DefineConstants>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ApplicationIcon />
        <Win32Resource />
        <AssemblyName>TheOtherRolesGM</AssemblyName>
		<AmongUs>H:\AmongUs\AmongUs</AmongUs>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\CustomHats\*.png" />
		<EmbeddedResource Include="Resources\*.png" />
		<EmbeddedResource Include="Resources\*.json" />
        <EmbeddedResource Include="Resources\TricksterAnimation\*.png" />
    </ItemGroup>

	<ItemGroup>
		<PackageReference Include="AmongUs.GameLibs.Steam" Version="2024.10.29" />
		<PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.670" Private="false" ExcludeAssets="runtime;native" />
		<PackageReference Include="BepInEx.IL2CPP.MSBuild" Version="2.0.1" PrivateAssets="all" ExcludeAssets="runtime" />
	</ItemGroup>


	<Target Name="CopyCustomContent" AfterTargets="AfterBuild">
        <Message Text="Second occurrence" />
        <Copy SourceFiles="$(ProjectDir)\bin\$(Configuration)\net6.0\TheOtherRolesGM.dll" DestinationFolder="$(AmongUs)/BepInEx/plugins/" />
    </Target>
<!--
    <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
      <Exec Command="py &quot;$(SolutionDir)stringsToJson.py&quot;" />
    </Target>
-->
</Project>
